enable:
  - govet
  - gosimple
  - ineffassign
  - staticcheck
  - unused
  - errcheck

linters-settings:
  govet:
    check-shadowing: true
  staticcheck:
    checks: ["all"]

run:
  timeout: 3m
  issues-exit-code: 1
  tests: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
